INSERT INTO public."Basic_country"(
	id, "registrationDate", "updateDate", "codeIBGE", name, acronym, nationality, "isActive")
	VALUES
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '004', 'Afeganistão', 'AFG', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '710','África do Sul','ZAF', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '008','Albânia','ALB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '276','Alemanha','DEU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '020','Andorra','AND', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '024','Angola','AGO', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '660','Anguilla','AIA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '028','Antígua e Barbuda','ATG', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '682','Arábia Saudita','SAU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '012','Argélia','DZA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '032','Argentina','ARG', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '051','Armênia','ARM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '533','Aruba','ABW', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '036','Austrália','AUS', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '040','Áustria','AUT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '031','Azerbaijão','AZE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '044','Bahamas','BHS', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '050','Bangladesh','BGD', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '052','Barbados','BRB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '048','Barein','BHR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '056','Bélgica','BEL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '084','Belize','BLZ', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '204','Benin','BEN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '060','Bermuda','BMU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '112','Bielorússia','BLR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '068','Bolívia','BOL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '535','Bonaire, Santo Eustáquio e Saba','BES', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '070','Bósnia-Herzegovina','BIH', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '072','Botsuana','BWA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '076','Brasil','BRA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '096','Brunei','BRN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '100','Bulgária','BGR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '854','Burkina Faso','BFA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '108','Burundi','BDI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '064','Butão','BTN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '132','Cabo Verde','CPV', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '120','Camarões','CMR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '124','Canadá','CAN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '398','Casaquistão','KAZ', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '634','Catar','QAT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '148','Chade','TCD', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '152','Chile','CHL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '156','China','CHN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '344','China, Hong Kong','HKG', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '446','China, Macao','MAC', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '196','Chipre','CYP', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '702','Cingapura','SGP', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '170','Colômbia','COL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '174','Comores','COM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '178','Congo','COG', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '408','Coréia do Norte','PRK', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '410','Coréia do Sul','KOR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '384','Costa do Marfim','CIV', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '188','Costa Rica','CRI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '191','Croácia','HRV', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '192','Cuba','CUB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '531','Curaçao','CUW', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '208','Dinamarca','DNK', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '262','Djibouti','DJI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '212','Dominica','DMA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '818','Egito','EGY', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '222','El Salvador','SLV', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '784','Emirados Árabes Unidos','ARE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '218','Equador','ECU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '232','Eritréia','ERI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '703','Eslováquia','SVK', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '705','Eslovênia','SVN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '724','Espanha','ESP', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '840','Estados Unidos da América','USA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '233','Estônia','EST', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '231','Etiópia','ETH', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '242','Fiji','FJI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '608','Filipinas','PHL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '246','Finlândia','FIN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '250','França','FRA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '266','Gabão','GAB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '270','Gâmbia','GMB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '288','Gana','GHA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '268','Geórgia','GEO', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '292','Gibraltar','GIB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '308','Granada','GRD', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '300','Grécia','GRC', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '304','Groenlândia','GRL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '316','Guam','GUM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '320','Guatemala','GTM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '831','Guernsey','GGY', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '328','Guiana','GUY', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '254','Guiana Francesa','GUF', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '324','Guiné','GIN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '226','Guiné Equatorial','GNQ', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '624','Guiné-Bissau','GNB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '332','Haiti','HTI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '528','Holanda','NLD', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '340','Honduras','HND', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '348','Hungria','HUN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '887','Iêmen','YEM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '833','Ilha de Man','IMN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '312','Ilha Guadalupe','GLP', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '574','Ilha Norfolk','NFK', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '638','Ilha Reunião','REU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '248','Ilhas Alanda','ALA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '136','Ilhas Cayman','CYM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '184','Ilhas Cook','COK', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '830','Ilhas do Canal', '!!!', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '234','Ilhas Faeroe','FRO', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '238','Ilhas Falkland','FLK', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '580','Ilhas Marianas','MNP', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '584','Ilhas Marshall','MHL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '090','Ilhas Salomão','SLB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '796','Ilhas Turks e Caicos','TCA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '850','Ilhas Virgens','VIR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '092','Ilhas Virgens Britânicas','VGB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '876','Ilhas Wallis e Futuna','WLF', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '356','Índia','IND', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '360','Indonésia','IDN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '364','Irã','IRN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '368','Iraque','IRQ', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '372','Irlanda','IRL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '352','Islândia','ISL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '376','Israel','ISR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '380','Itália','ITA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '388','Jamaica','JAM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '392','Japão','JPN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '832','Jersey','JEY', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '400','Jordânia','JOR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '296','Kiribati','KIR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '414','Kuwait','KWT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '418','Laos','LAO', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '426','Lesoto','LSO', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '428','Letônia','LVA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '422','Líbano','LBN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '430','Libéria','LBR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '434','Líbia','LBY', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '438','Liechtenstein','LIE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '440','Lituânia','LTU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '442','Luxemburgo','LUX', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '807','Macedônia','MKD', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '450','Madagáscar','MDG', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '458','Malásia','MYS', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '454','Malauí','MWI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '462','Maldivas','MDV', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '466','Mali','MLI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '470','Malta','MLT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '504','Marrocos','MAR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '474','Martinica','MTQ', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '480','Maurício','MUS', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '478','Mauritânia','MRT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '175','Mayotte','MYT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '484','México','MEX', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '104','Mianma','MMR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '583','Micronésia','FSM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '508','Moçambique','MOZ', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '498','Moldávia','MDA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '492','Mônaco','MCO', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '496','Mongólia','MNG', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '499','Montenegro','MNE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '500','Montserrat','MSR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '516','Namíbia','NAM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '520','Nauru','NRU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '524','Nepal','NPL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '558','Nicarágua','NIC', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '562','Níger','NER', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '566','Nigéria','NGA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '570','Niue','NIU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '578','Noruega','NOR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '540','Nova Caledônia','NCL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '554','Nova Zelândia','NZL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '512','Omã','OMN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '585','Palau','PLW', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '275','Palestina','PSE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '591','Panamá','PAN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '598','Papua Nova Guiné','PNG', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '586','Paquistão','PAK', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '600','Paraguai','PRY', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '604','Peru','PER', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '612','Pitcairn','PCN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '258','Polinésia Francesa','PYF', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '616','Polônia','POL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '630','Porto Rico','PRI', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '620','Portugal','PRT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '404','Quênia','KEN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '417','Quirguistão','KGZ', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '826','Reino Unido','GBR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '140','República Centro Africana','CAF', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '180','República Democrática do Congo','COD', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '214','República Dominicana','DOM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '203','República Tcheca','CZE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '642','Romênia','ROU', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '646','Ruanda','RWA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '643','Rússia (Federação Russa)','RUS', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '732','Saara Ocidental','ESH', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '663','Saint Martin (parte francesa)','MAF', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '534','Saint Martin (parte holandesa)','SXM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '666','Saint Pierre e Miquelon','SPM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '882','Samoa','WSM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '016','Samoa Americana','ASM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '674','San Marino','SMR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '654','Santa Helena','SHN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '662','Santa Lúcia','LCA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '652','São Bartolomeu','BLM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '659', 'São Cristóvão e Nevis','KNA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '678', 'São Tome e Príncipe', 'STP', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '670', 'São Vicente e Granadinas', 'VCT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '680', 'Sark', '???', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '690', 'Seichelles', 'SYC', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '686', 'Senegal', 'SEN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '694', 'Serra Leoa', 'SLE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '688', 'Sérvia', 'SRB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '760', 'Síria', 'SYR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '706', 'Somália', 'SOM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '144', 'Sri Lanka', 'LKA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '748', 'Suazilândia', 'SWZ', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '728', 'Sudão do Sul', 'SSD', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '729', 'Sudão', 'SDN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '752', 'Suécia', 'SWE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '756', 'Suíça', 'CHE', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '740', 'Suriname', 'SUR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '744', 'Svalbard e Jan Mayen Islands', 'SJM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '762', 'Tadjiquistão', 'TJK', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '764', 'Tailândia', 'THA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '834', 'Tanzânia', 'TZA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '626', 'Timor Leste', 'TLS', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '768', 'Togo', 'TGO', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '772', 'Tokelau', 'TKL', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '776', 'Tonga', 'TON', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '780', 'Trinidad e Tobago', 'TTO', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '788', 'Tunísia', 'TUN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '795', 'Turcomenistão', 'TKM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '792', 'Turquia', 'TUR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '798', 'Tuvalu', 'TUV', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '804', 'Ucrânia', 'UKR', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '800', 'Uganda', 'UGA', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '858', 'Uruguai', 'URY', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '860', 'Uzbequistão', 'UZB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '548', 'Vanuatu', 'VUT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '336', 'Vaticano', 'VAT', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '862', 'Venezuela', 'VEN', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '704', 'Vietnã', 'VNM', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '894', 'Zâmbia', 'ZMB', null, True),
	(nextval('"Basic_country_id_seq"'::regclass), CURRENT_DATE, CURRENT_DATE, '716', 'Zimbábue', 'ZWE', null, True);