# Generated by Django 4.0.5 on 2022-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0003_phone_address'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalPersonPhone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Basic.phone')),
                ('physicalPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.physicalperson', verbose_name='Verbose Physical Person')),
            ],
            options={
                'verbose_name': 'Verbose Phone',
                'verbose_name_plural': 'Verbose Phone Plural',
            },
            bases=('Basic.phone',),
        ),
        migrations.CreateModel(
            name='PhysicalPersonAddress',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Basic.address')),
                ('physicalPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.physicalperson', verbose_name='Verbose Physical Person')),
            ],
            options={
                'verbose_name': 'Verbose Address',
                'verbose_name_plural': 'Verbose Address Plural',
            },
            bases=('Basic.address',),
        ),
    ]
