# Generated by Django 4.0.4 on 2022-05-22 16:43

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Registration Date')),
                ('updateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Update Date')),
                ('isActive', models.BooleanField(default=True, verbose_name='Verbose Is Active')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Verbose Description')),
            ],
            options={
                'verbose_name': 'Verbose Permission Group',
                'verbose_name_plural': 'Verbose Permission Group Plural',
                'ordering': ['name'],
            },
            bases=('auth.group', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
