# Generated by Django 4.0.4 on 2022-05-23 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Verbose ID')),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Registration Date')),
                ('updateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Update Date')),
                ('isActive', models.BooleanField(default=True, verbose_name='Verbose Is Active')),
                ('codeIBGE', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='Verbose Code IBGE')),
                ('name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Verbose Name')),
                ('acronym', models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)], verbose_name='Verbose Acronym')),
                ('nationality', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Verbose Nationality')),
            ],
            options={
                'verbose_name': 'Verbose Country',
                'verbose_name_plural': 'Verbose Country Plural',
                'ordering': ['name', 'codeIBGE', 'acronym'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Verbose ID')),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Registration Date')),
                ('updateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Update Date')),
                ('isActive', models.BooleanField(default=True, verbose_name='Verbose Is Active')),
                ('codeIBGE', models.CharField(max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)], verbose_name='Verbose Code IBGE')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Verbose Name')),
                ('acronym', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)], verbose_name='Verbose Acronym')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Basic.country', verbose_name='Verbose Country')),
            ],
            options={
                'verbose_name': 'Verbose State',
                'verbose_name_plural': 'Verbose State Plural',
                'ordering': ['name', 'codeIBGE', 'acronym'],
                'unique_together': {('name', 'country'), ('acronym', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Verbose ID')),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Registration Date')),
                ('updateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Update Date')),
                ('isActive', models.BooleanField(default=True, verbose_name='Verbose Is Active')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Verbose Name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Basic.state', verbose_name='Verbose State')),
            ],
            options={
                'verbose_name': 'Verbose Territory',
                'verbose_name_plural': 'Verbose Territory Plural',
                'ordering': ['name'],
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Verbose ID')),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Registration Date')),
                ('updateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Update Date')),
                ('isActive', models.BooleanField(default=True, verbose_name='Verbose Is Active')),
                ('codeIBGE', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)], verbose_name='Verbose Code IBGE')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Verbose Name')),
                ('isCapital', models.BooleanField(default=False, verbose_name='Verbose Is Capital')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Basic.state', verbose_name='Verbose State')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Basic.territory', verbose_name='Verbose Territory')),
            ],
            options={
                'verbose_name': 'Verbose City',
                'verbose_name_plural': 'Verbose City Plural',
                'ordering': ['name', 'codeIBGE'],
                'unique_together': {('name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Verbose ID')),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Registration Date')),
                ('updateDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Verbose Update Date')),
                ('isActive', models.BooleanField(default=True, verbose_name='Verbose Is Active')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(200)], verbose_name='Verbose Name')),
                ('zone', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='Verbose Zone')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Basic.city', verbose_name='Verbose City')),
            ],
            options={
                'verbose_name': 'Verbose Neighborhood',
                'verbose_name_plural': 'Verbose Neighborhood Plural',
                'ordering': ['name'],
                'unique_together': {('name', 'city')},
            },
        ),
    ]
